version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres+asyncpg://postgres:postgres@db:5432/booking
    volumes:
      - .:/app

volumes:
  pg_data:
